### PR TITLE
fix(DateTimeLabelFormatSerializer) quote issues

### PR DESCRIPTION
**Pull request by age2pierre**
Currently the serializer returns
```
"dateTimeLabelFormats" : { minute: '%H:%M:%S', day: '%H:%M:%S', week: '%H:%M:%S', year: '%H:%M:%S', second: '%H:%M:%S', hour: '%H:%M:%S' },
```
which is not not valid json (but ok as json5 though ;)

### CODE REVIEW

**Comment by maximAtanasov** [comment]
Hello @age2pierre ,
Thanks for the PR.
Some tests are failing, if you could adjust those, then I can merge the PR.

**Comment by age2pierre** [comment]
Hello, @maximAtanasov sorry i left this PR hanging for so long I kinda forgot about it. I've fixed the tests, it should be all good now. Also I've removed the commits about openJDK8 for travis, it did not seem to work anymore.

**Comment by age2pierre** [comment]
> it should be all good now

Well almost, I have a message `This branch is out-of-date with the base branch` and yet it seems I'm up-to-date :/
image

And when i click on the button `update branch` it brings me back from the dead the commit about openJDK...

**Comment by maximAtanasov** [comment]
Hello @age2pierre , thanks for updating the tests. I've updated the branch manually so it should be fine now :)

**Pull request merged**
